### ISSUE TITLE
tests fail on debian due to hard coded paths.

### ISSUE THREAD

**Issue by pravi** [jonschlinkert/global-modules#5]
```
mocha -R spec


  mods
    1) should resolve the path to the global npm modules directory:


  0 passing (20ms)
  1 failing

  1) mods should resolve the path to the global npm modules directory::
     AssertionError: false == true
      at Context.<anonymous> (/<<PKGBUILDDIR>>/test.js:17:5)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:223:21)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:216:7)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:373:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:451:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:298:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:308:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:246:23)
      at Immediate._onImmediate (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)
```

On debian the global modules path is /usr/lib/nodejs. Its similar to https://github.com/jonschlinkert/global-prefix/issues/15

**Comment by pravi** [comment]
I have patched the debian package and if that is all required, I can close this issue.

**Comment by pravi** [comment]
On debian, packaged executable is "nodejs" instead of "node", probably we could use that to identify debian.

**Comment by jonschlinkert** [comment]
> probably we could use that to identify debian.

Do you want to do a pr?
