### ISSUE TITLE
Too many caught exceptions

### ISSUE THREAD

**Issue by BurtHarris** [jonschlinkert/global-modules#6]
Trying to debug a gulp script, I enabled breakpoints on all exceptions.     There were a large number of exceptions from the global-modules package.    If you can change the implementation to avoid this, it would make this a better package.

P.S.   It would also be nice if you adopt semver and bump the version number to 1, semver rules say version 0 is reserved effectively excluded from versioning.

**Comment by BurtHarris** [comment]
Exception has occurred: Error
    Error: ENOENT: no such file or directory, stat 'c:\code\antlr4ts\npm.COM'
    at Object.fs.statSync (fs.js:940:11)
    at Function.sync (c:\code\antlr4ts\node_modules\isexe\windows.js:41:23)
    at Function.sync (c:\code\antlr4ts\node_modules\isexe\index.js:49:17)
    at Function.whichSync [as sync] (c:\code\antlr4ts\node_modules\which\which.js:117:20)
    at npmPath (c:\code\antlr4ts\node_modules\global-prefix\index.js:67:45)
    at Object.<anonymous> (c:\code\antlr4ts\node_modules\global-prefix\index.js:30:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by BurtHarris** [comment]
Looking at the stack, perhaps its not your module generating the error, but I guess catching it.

**Comment by BurtHarris** [comment]
Looking at the stack I guess its not your module throwing the exception, I'll try to chase this down further...

    Exception has occurred: Error
    Error: ENOENT: no such file or directory, stat 'c:\code\antlr4ts\npm.COM'
    at Object.fs.statSync (fs.js:940:11)
    at Function.sync (c:\code\antlr4ts\node_modules\isexe\windows.js:41:23)
    at Function.sync (c:\code\antlr4ts\node_modules\isexe\index.js:49:17)
    at Function.whichSync [as sync] (c:\code\antlr4ts\node_modules\which\which.js:117:20)
    at npmPath (c:\code\antlr4ts\node_modules\global-prefix\index.js:67:45)
    at Object.<anonymous> (c:\code\antlr4ts\node_modules\global-prefix\index.js:30:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by BurtHarris** [comment]
I filed a lower-level bug isaacs/isexe#12
